spring:
  security:
    user:
      name: babookjy
      password: 1234
        
  dataSource:
    url: http://localhost:3306
    sername: root
    password: 6327331cn
    driverClassName: com.mysql.jdbc.Driver